// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUYiYbnA9Vs8irYwXhGUYpJLJLCbzLrvc',
    appId: '1:563483897269:web:92b78cbc405629f5b47dfc',
    messagingSenderId: '563483897269',
    projectId: 'flutter-login-bloc-1b70b',
    authDomain: 'flutter-login-bloc-1b70b.firebaseapp.com',
    storageBucket: 'flutter-login-bloc-1b70b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTLXP48z_kmqBetc8S0al5S9eKbvS-wEI',
    appId: '1:563483897269:android:95b05b55bbdcc970b47dfc',
    messagingSenderId: '563483897269',
    projectId: 'flutter-login-bloc-1b70b',
    storageBucket: 'flutter-login-bloc-1b70b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzy091oJrZs5ow3ZYI-zKHnCHOt6TreOA',
    appId: '1:563483897269:ios:c8544c3cdfdd8d9cb47dfc',
    messagingSenderId: '563483897269',
    projectId: 'flutter-login-bloc-1b70b',
    storageBucket: 'flutter-login-bloc-1b70b.appspot.com',
    iosClientId: '563483897269-smd9rj2aqk63sa4adi1frq0ls01v0r6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.flutter-firebase-login',
  );
}
